apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: spot-oceancd-operator-subscription
spec:
  channel: {{ .Values.caBundle }}
  name: spot-oceancd-operator
  source: spot-oceancd-catalog
  sourceNamespace: {{ .Release.Namespace }}